In [15]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings("ignore", category=FutureWarning)

In [16]:
df = pd.read_excel('Iris.xls')
df.head()

sepal length  sepal width  petal length  petal width         iris
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [17]:
x = df.iloc[:, 0:4]
y = df.iloc[:, 4:]

x_values = x.values
y_values = y.values.ravel()

In [18]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x_values, y_values, test_size=0.33, random_state=0)

In [19]:
from sklearn.preprocessing import StandardScaler

ss = StandardScaler()
X_train = ss.fit_transform(x_train)
X_test = ss.transform(x_test)

In [20]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors = 10, metric = 'minkowski')
knn.fit(X_train, y_train)
preds_knn = knn.predict(X_test)

In [21]:
from sklearn.metrics import confusion_matrix

cm_knn = confusion_matrix(y_test, preds_knn)
cm_knn

array([[16,  0,  0],
       [ 0, 18,  1],
       [ 0,  1, 14]])

In [22]:
from sklearn.svm import SVC
svc = SVC(kernel = 'linear') #best sol for this data : linear  
#svc = SVC(kernel = 'rbf') : 2 false
svc.fit(X_train, y_train)

preds_svc = svc.predict(X_test)

In [23]:
cm_svc = confusion_matrix(y_test, preds_svc)
cm_svc

array([[16,  0,  0],
       [ 0, 18,  1],
       [ 0,  0, 15]])

In [24]:
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression(random_state = 0)
log_reg.fit(X_train, y_train)

preds_log_reg = log_reg.predict(X_test)

In [25]:
cm_log_reg = confusion_matrix(y_test, preds_log_reg)
cm_log_reg

array([[16,  0,  0],
       [ 0, 13,  6],
       [ 0,  2, 13]])

In [26]:
from sklearn.tree import DecisionTreeClassifier
dec_tree = DecisionTreeClassifier() #default criterion= gini | nbr of falses = 1
#dec_tree = DecisionTreeClassifier(criterion='entropy') # nbr of falses = 2

dec_tree.fit(X_train, y_train)
preds_dt = dec_tree.predict(X_test)

In [27]:
cm_dt = confusion_matrix(y_test, preds_dt)
cm_dt

array([[16,  0,  0],
       [ 0, 18,  1],
       [ 0,  1, 14]])

In [28]:
from sklearn.ensemble import RandomForestClassifier
ran_forest = RandomForestClassifier(n_estimators=10) #nbr of falses : 2
#ran_forest = RandomForestClassifier(n_estimators=10, criterion='entropy') #nbr of falses : 3

ran_forest.fit(X_train, y_train)
preds_rf = ran_forest.predict(X_test)

In [29]:
cm_rf = confusion_matrix(y_test, preds_rf)
cm_rf

array([[16,  0,  0],
       [ 0, 18,  1],
       [ 0,  1, 14]])

In [30]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()

gnb.fit(X_train, y_train)
preds_gnb = gnb.predict(X_test)

In [31]:
cm_gnb = confusion_matrix(y_test, preds_gnb)
cm_gnb

array([[16,  0,  0],
       [ 0, 19,  0],
       [ 0,  2, 13]])

In [32]:
from sklearn.metrics import accuracy_score

print('-The accuracy scores-')
print('Logistic Regression : ', accuracy_score(y_test, preds_log_reg))
print('KNN : ', accuracy_score(y_test, preds_knn))
print('SVC : ', accuracy_score(y_test, preds_svc))
print('Decision Tree : ', accuracy_score(y_test, preds_dt))
print('Random Forest : ', accuracy_score(y_test, preds_rf))
print('Gaussian Naive Bayes : ', accuracy_score(y_test, preds_gnb))

-The accuracy scores-
Logistic Regression :  0.84
KNN :  0.96
SVC :  0.98
Decision Tree :  0.96
Random Forest :  0.96
Gaussian Naive Bayes :  0.96


In [33]:
#best score
scores = []
scores = [accuracy_score(y_test, preds_log_reg), accuracy_score(y_test, preds_knn),
         accuracy_score(y_test, preds_svc), accuracy_score(y_test, preds_dt),
         accuracy_score(y_test, preds_rf), accuracy_score(y_test, preds_gnb)]
scores

[0.84, 0.96, 0.98, 0.96, 0.96, 0.96]

In [34]:
max_score = 0
for i in scores:
    if max_score <= i:
        max_score = i
        
print('The best accuracy for Iris data : ',max_score)

The best accuracy for Iris data :  0.98
